name: Deploy OSLab


on:
  workflow_run:
    workflows: ["OSLab Laravel Application Test"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Git Pull no Servidor
        run: |
          cd /var/Docker/Docker_Dev_Web/www/oslab
          git pull origin main

      - name: Rodar Composer dentro do diretório Oslab
        run: |
          sudo docker exec app composer install -d oslab

      - name: Rodar Artisan Migrate
        run: |
          sudo docker exec app php oslab/artisan migrate

      - name: Rodar Artisan db:update-defaults (chamando direto na classe)
        run: |
          sudo docker exec app php oslab/artisan db:seed --class DatabaseDefaultPermissionsUpdate
