name: Deploy OSLab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Usa o runner que configuramos no servidor

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Git Pull no Servidor
        run: |
          cd /var/Docker/Docker_Dev_Web/www/oslab
          git pull origin main

      - name: Rodar Composer dentro do diretório Oslab
        run: |
          sudo docker compose exec app sh -c "cd /var/www/oslab && composer install --no-interaction"

      - name: Rodar Artisan Migrate
        run: |
          sudo docker compose exec app php oslab/artisan migrate

      - name: Rodar Artisan db:update-defaults (chamando direto na classe)
        run: |
          sudo docker compose exec app php oslab/artisan db:seed --class DatabaseDefaultPermissionsUpdate
