name: Deploy OSLab


on:
  workflow_run:
    workflows: ["OSLab Laravel Application Test"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Git Pull no Servidor
        run: |
          cd /var/Docker/Docker_Dev_Web/www/oslab
          git pull origin main

      - name: Gerar e Injetar Versão no .env
        run: |
          # Lê a base do arquivo version.env
          BASE=$(grep -E "^BASE_VERSION=" version.env | cut -d '=' -f2 | tr -d '\r')

          # Dados para a versão visual
          BRANCH=${{ github.ref_name }}
          SHORT_HASH=$(echo ${{ github.sha }} | cut -c1-7)

          # Dados para a URL do GitHub
          FULL_HASH=${{ github.sha }}
          REPO=${{ github.repository }} # Retorna repositório no formato "owner/repo"

          # Salva no .env
          echo "APP_VERSION=${BASE}-${BRANCH}-${SHORT_HASH}" >> .env
          echo "APP_VERSION_URL=https://github.com/${REPO}/commit/${FULL_HASH}" >> .env

      - name: Rodar Composer dentro do diretório Oslab
        run: |
          sudo docker exec app composer install -d oslab

      - name: Rodar Artisan Migrate
        run: |
          sudo docker exec app php oslab/artisan migrate

      - name: Limpando cache de configuração
        run: |
          sudo docker exec app php oslab/artisan optimize:clear

      - name: Rodar Artisan db:update-defaults (chamando direto na classe)
        run: |
          sudo docker exec app php oslab/artisan db:seed --class DatabaseDefaultPermissionsUpdate
